# Generated by Django 4.2.3 on 2023-07-30 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGymGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('image', models.ImageField(blank=True, default='gym_gallery/gym_image.png', null=True, upload_to='gym_gallery/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdminVideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('url', models.CharField(default='', max_length=512)),
                ('thumbnail', models.ImageField(blank=True, default='gym_video_gallery/gym_video_image.png', null=True, upload_to='gym_video_gallery/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FitHubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('designation', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('joining_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GymInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, default='gym_information/logo.png', null=True, upload_to='gym_information/')),
                ('about_us', models.TextField(blank=True, null=True)),
                ('administators', models.ManyToManyField(blank=True, null=True, related_name='administrators', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='gym_members', to=settings.AUTH_USER_MODEL)),
                ('trainers', models.ManyToManyField(blank=True, null=True, related_name='trainers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('url', models.CharField(default='', max_length=512)),
                ('thumbnail', models.ImageField(blank=True, default='gym_video_gallery/gym_video_image.png', null=True, upload_to='gym_video_gallery/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('gym_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.gyminformation')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('gym_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.gyminformation')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('gym_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.gyminformation')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.fithubmember')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.plan')),
            ],
        ),
        migrations.CreateModel(
            name='GymMemberVideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('url', models.CharField(default='', max_length=512)),
                ('thumbnail', models.ImageField(blank=True, default='gym_video_gallery/gym_video_image.png', null=True, upload_to='gym_video_gallery/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('gym_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.gyminformation')),
            ],
        ),
        migrations.AddField(
            model_name='fithubmember',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.plan'),
        ),
        migrations.AddField(
            model_name='fithubmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('image', models.ImageField(blank=True, default='equipments/equipment_image.png', null=True, upload_to='equipments/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('gym_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.gyminformation')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('image', models.ImageField(blank=True, default='equipments/equipment_image.png', null=True, upload_to='equipments/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('gym_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.gyminformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.fithubmember')),
            ],
        ),
        migrations.CreateModel(
            name='DietChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('image', models.ImageField(blank=True, default='diet_chart/diet_chart_image.png', null=True, upload_to='diet_chart/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('diet_chart_date', models.DateTimeField(auto_now=True)),
                ('gym_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.gyminformation')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.fithubmember')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
