# Generated by Django 4.2.3 on 2023-08-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitHubManageApp', '0002_gymadministator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gyminformation',
            name='administators',
        ),
        migrations.RemoveField(
            model_name='gyminformation',
            name='trainers',
        ),
    ]
