# Generated by Django 4.2.3 on 2023-08-04 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FitHubManageApp', '0003_remove_gyminformation_administators_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.gyminformation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
