# Generated by Django 4.2.3 on 2023-08-04 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FitHubManageApp', '0004_gymtrainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_trainer', models.BooleanField(default=False)),
                ('is_normal_member', models.BooleanField(default=False)),
                ('gym_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.gyminformation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
