# Generated by Django 4.2.3 on 2023-08-05 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitHubManageApp', '0005_gymmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=512)),
                ('image', models.ImageField(blank=True, default='blog/blog_image.png', null=True, upload_to='blog/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('blog_date', models.DateTimeField(auto_now=True)),
                ('gym_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.gyminformation')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.gymadministator')),
            ],
        ),
    ]
