# Generated by Django 4.2.3 on 2023-08-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitHubManageApp', '0006_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='sort_order',
        ),
    ]
