# Generated by Django 4.2.3 on 2023-08-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitHubManageApp', '0007_remove_blog_sort_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='trainer',
            new_name='admin',
        ),
    ]
