# Generated by Django 4.2.3 on 2023-08-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitHubManageApp', '0008_rename_trainer_blog_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='gym_info',
        ),
    ]
