# Generated by Django 4.2.3 on 2023-08-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitHubManageApp', '0010_alter_blog_description_alter_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipments',
            name='sort_order',
        ),
    ]
