# Generated by Django 4.2.3 on 2023-08-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHubManageApp', '0011_remove_equipments_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
    ]
