# Generated by Django 4.2.3 on 2023-08-07 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitHubManageApp', '0013_equipments_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fithubmember',
            name='email',
        ),
        migrations.AddField(
            model_name='fithubmember',
            name='gym_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.gyminformation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fithubmember',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fithubmember',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True),
        ),
    ]
