# Generated by Django 4.2.3 on 2023-08-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHubManageApp', '0014_remove_fithubmember_email_fithubmember_gym_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fithubmember',
            name='plan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
