# Generated by Django 4.2.3 on 2023-08-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitHubManageApp', '0015_fithubmember_plan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='gym_info',
        ),
    ]
