# Generated by Django 4.2.3 on 2023-08-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitHubManageApp', '0016_remove_payment_gym_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmember',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
