# Generated by Django 4.2.3 on 2023-08-08 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitHubManageApp', '0017_gymmember_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
    ]
