# Generated by Django 4.2.3 on 2023-08-09 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitHubManageApp', '0018_remove_payment_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.equipments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitHubManageApp.fithubmember')),
            ],
        ),
    ]
